export class Album {
  public static data = {
    'albums': {
      'href': 'https://api.spotify.com/v1/search?query=muse&type=album&market=IT&offset=0&limit=20',
      'items': [
        {
          'album_type': 'album',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI'
              },
              'href': 'https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI',
              'id': '12Chz98pHFMPJEknJQMWvI',
              'name': 'Muse',
              'type': 'artist',
              'uri': 'spotify:artist:12Chz98pHFMPJEknJQMWvI'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/5OZgDtx180ZZPMpm36J2zC'
          },
          'href': 'https://api.spotify.com/v1/albums/5OZgDtx180ZZPMpm36J2zC',
          'id': '5OZgDtx180ZZPMpm36J2zC',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/0b15f63923b517c1ebd65b58b903327b297293c3',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/98ce46f08cf1083fbcfae03f150b8e19b38289b6',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/28a8487234c901ae9fe127d1d0eef738a91e46d6',
              'width': 64
            }
          ],
          'name': 'Simulation Theory (Super Deluxe)',
          'release_date': '2018-11-09',
          'release_date_precision': 'day',
          'total_tracks': 21,
          'type': 'album',
          'uri': 'spotify:album:5OZgDtx180ZZPMpm36J2zC'
        },
        {
          'album_type': 'album',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI'
              },
              'href': 'https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI',
              'id': '12Chz98pHFMPJEknJQMWvI',
              'name': 'Muse',
              'type': 'artist',
              'uri': 'spotify:artist:12Chz98pHFMPJEknJQMWvI'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/0lw68yx3MhKflWFqCsGkIs'
          },
          'href': 'https://api.spotify.com/v1/albums/0lw68yx3MhKflWFqCsGkIs',
          'id': '0lw68yx3MhKflWFqCsGkIs',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/9e5288926fadb82f873ccf2b45300c3a6f65fa14',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/f1cad0d6974d6236abd07a59106e8450d85cae24',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/81a3f82578dc938c53efdcb405f6a3d3ebbf009f',
              'width': 64
            }
          ],
          'name': 'Black Holes And Revelations',
          'release_date': '2006-06-19',
          'release_date_precision': 'day',
          'total_tracks': 12,
          'type': 'album',
          'uri': 'spotify:album:0lw68yx3MhKflWFqCsGkIs'
        },
        {
          'album_type': 'album',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI'
              },
              'href': 'https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI',
              'id': '12Chz98pHFMPJEknJQMWvI',
              'name': 'Muse',
              'type': 'artist',
              'uri': 'spotify:artist:12Chz98pHFMPJEknJQMWvI'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/0eFHYz8NmK75zSplL5qlfM'
          },
          'href': 'https://api.spotify.com/v1/albums/0eFHYz8NmK75zSplL5qlfM',
          'id': '0eFHYz8NmK75zSplL5qlfM',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/6e1be3ceda70250c701caee5a16bef205e94bc98',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/28752dcf4b27ba14c1fc62f04ff469aa53c113d7',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/26098aaa50a3450f0bac8f1a7d7677accf3f3cb6',
              'width': 64
            }
          ],
          'name': 'The Resistance',
          'release_date': '2009-09-10',
          'release_date_precision': 'day',
          'total_tracks': 11,
          'type': 'album',
          'uri': 'spotify:album:0eFHYz8NmK75zSplL5qlfM'
        },
        {
          'album_type': 'album',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI'
              },
              'href': 'https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI',
              'id': '12Chz98pHFMPJEknJQMWvI',
              'name': 'Muse',
              'type': 'artist',
              'uri': 'spotify:artist:12Chz98pHFMPJEknJQMWvI'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/3KuXEGcqLcnEYWnn3OEGy0'
          },
          'href': 'https://api.spotify.com/v1/albums/3KuXEGcqLcnEYWnn3OEGy0',
          'id': '3KuXEGcqLcnEYWnn3OEGy0',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/59fbbabeecaade686c44c99e5d1102130556bba1',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/ca0f14d8190f1cfc7183884a65af00ccd3e2301e',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/44b74728e87b87c44f91f505758cad882573d7ea',
              'width': 64
            }
          ],
          'name': 'The 2nd Law',
          'release_date': '2012-09-24',
          'release_date_precision': 'day',
          'total_tracks': 13,
          'type': 'album',
          'uri': 'spotify:album:3KuXEGcqLcnEYWnn3OEGy0'
        },
        {
          'album_type': 'album',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI'
              },
              'href': 'https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI',
              'id': '12Chz98pHFMPJEknJQMWvI',
              'name': 'Muse',
              'type': 'artist',
              'uri': 'spotify:artist:12Chz98pHFMPJEknJQMWvI'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/0HcHPBu9aaF1MxOiZmUQTl'
          },
          'href': 'https://api.spotify.com/v1/albums/0HcHPBu9aaF1MxOiZmUQTl',
          'id': '0HcHPBu9aaF1MxOiZmUQTl',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/ae61915fc3f4b3019200ba6ee58a2a85866461bf',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/523194c8f4f32d0d091a7686fea8fda0411b25a5',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/700cdaab602da14c4f007ad2f9cefcbd9292ac24',
              'width': 64
            }
          ],
          'name': 'Absolution',
          'release_date': '2004-03-23',
          'release_date_precision': 'day',
          'total_tracks': 15,
          'type': 'album',
          'uri': 'spotify:album:0HcHPBu9aaF1MxOiZmUQTl'
        },
        {
          'album_type': 'album',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI'
              },
              'href': 'https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI',
              'id': '12Chz98pHFMPJEknJQMWvI',
              'name': 'Muse',
              'type': 'artist',
              'uri': 'spotify:artist:12Chz98pHFMPJEknJQMWvI'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/2wart5Qjnvx1fd7LPdQxgJ'
          },
          'href': 'https://api.spotify.com/v1/albums/2wart5Qjnvx1fd7LPdQxgJ',
          'id': '2wart5Qjnvx1fd7LPdQxgJ',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/849eecf3c9df835181c2970c435ac2d008346ea3',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/8b6392caa83625135f0f53d6e2b0631bbe4c4c0b',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/8978459cc3ad68b39bd6dbda418625b06ba5d80c',
              'width': 64
            }
          ],
          'name': 'Drones',
          'release_date': '2015-06-04',
          'release_date_precision': 'day',
          'total_tracks': 12,
          'type': 'album',
          'uri': 'spotify:album:2wart5Qjnvx1fd7LPdQxgJ'
        },
        {
          'album_type': 'album',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI'
              },
              'href': 'https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI',
              'id': '12Chz98pHFMPJEknJQMWvI',
              'name': 'Muse',
              'type': 'artist',
              'uri': 'spotify:artist:12Chz98pHFMPJEknJQMWvI'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/1Dh27pjT3IEdiRG9Se5uQn'
          },
          'href': 'https://api.spotify.com/v1/albums/1Dh27pjT3IEdiRG9Se5uQn',
          'id': '1Dh27pjT3IEdiRG9Se5uQn',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/ecb609f80a433a4bcf06c42e69821772140f0632',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/1df08bc3fac0a95d783417bddba0bba9a1da579d',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/ea2eabc1ce63838531d746386cac28d2f9e3ce4c',
              'width': 64
            }
          ],
          'name': 'Origin Of Symmetry',
          'release_date': '2001',
          'release_date_precision': 'year',
          'total_tracks': 12,
          'type': 'album',
          'uri': 'spotify:album:1Dh27pjT3IEdiRG9Se5uQn'
        },
        {
          'album_type': 'album',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI'
              },
              'href': 'https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI',
              'id': '12Chz98pHFMPJEknJQMWvI',
              'name': 'Muse',
              'type': 'artist',
              'uri': 'spotify:artist:12Chz98pHFMPJEknJQMWvI'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/6AyUVv7MnxxTuijp4WmrhO'
          },
          'href': 'https://api.spotify.com/v1/albums/6AyUVv7MnxxTuijp4WmrhO',
          'id': '6AyUVv7MnxxTuijp4WmrhO',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/3e67c0e68b6cfa0e6d851e0492b29b968d6bb3b9',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/29a5e9fc13b9d5f7d5f78ba69d71afa23c84a9d5',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/fdd7655946d83f014ba2d2c2a3d89d7c7bdb2b64',
              'width': 64
            }
          ],
          'name': 'Showbiz',
          'release_date': '1999',
          'release_date_precision': 'year',
          'total_tracks': 13,
          'type': 'album',
          'uri': 'spotify:album:6AyUVv7MnxxTuijp4WmrhO'
        },
        {
          'album_type': 'album',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI'
              },
              'href': 'https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI',
              'id': '12Chz98pHFMPJEknJQMWvI',
              'name': 'Muse',
              'type': 'artist',
              'uri': 'spotify:artist:12Chz98pHFMPJEknJQMWvI'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/2m7L60M210ABzrY9GLyBPZ'
          },
          'href': 'https://api.spotify.com/v1/albums/2m7L60M210ABzrY9GLyBPZ',
          'id': '2m7L60M210ABzrY9GLyBPZ',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/05c049956ed66d6dd3451d9ac06e0f30ff1693b3',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/71a45fc4b9d8f4f5e0998751f7c29a97f5f0fdd3',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/680b385164b970b271365f2da1271bc642b77fb7',
              'width': 64
            }
          ],
          'name': 'Live At Rome Olympic Stadium',
          'release_date': '2013-11-25',
          'release_date_precision': 'day',
          'total_tracks': 13,
          'type': 'album',
          'uri': 'spotify:album:2m7L60M210ABzrY9GLyBPZ'
        },
        {
          'album_type': 'album',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/6FxuPrpa8phaP3Xn73emhT'
              },
              'href': 'https://api.spotify.com/v1/artists/6FxuPrpa8phaP3Xn73emhT',
              'id': '6FxuPrpa8phaP3Xn73emhT',
              'name': 'The Wood Brothers',
              'type': 'artist',
              'uri': 'spotify:artist:6FxuPrpa8phaP3Xn73emhT'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/2xkAdEXW7nGQAJMptaOk2d'
          },
          'href': 'https://api.spotify.com/v1/albums/2xkAdEXW7nGQAJMptaOk2d',
          'id': '2xkAdEXW7nGQAJMptaOk2d',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/afe446daa20f89d46cf63b5d5c43c2227104f216',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/2a19e9365f480f60243a7bb603b977adea4eb423',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/63099a2357dfa3d7057d20b4fcc910f71d8254da',
              'width': 64
            }
          ],
          'name': 'The Muse',
          'release_date': '2013',
          'release_date_precision': 'year',
          'total_tracks': 11,
          'type': 'album',
          'uri': 'spotify:album:2xkAdEXW7nGQAJMptaOk2d'
        },
        {
          'album_type': 'single',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI'
              },
              'href': 'https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI',
              'id': '12Chz98pHFMPJEknJQMWvI',
              'name': 'Muse',
              'type': 'artist',
              'uri': 'spotify:artist:12Chz98pHFMPJEknJQMWvI'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/2tJXza5ryx9DKIsmAI8neb'
          },
          'href': 'https://api.spotify.com/v1/albums/2tJXza5ryx9DKIsmAI8neb',
          'id': '2tJXza5ryx9DKIsmAI8neb',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/67e6893b57ababff1745f908a6861e6e449244b1',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/c7ddb9f873204d86e9671268979d88e477a84fe7',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/5d6ed87cb5b24d3bb1353dc1096ed25de86c884f',
              'width': 64
            }
          ],
          'name': 'Neutron Star Collision [Love Is Forever]',
          'release_date': '2010-05-17',
          'release_date_precision': 'day',
          'total_tracks': 1,
          'type': 'album',
          'uri': 'spotify:album:2tJXza5ryx9DKIsmAI8neb'
        },
        {
          'album_type': 'album',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI'
              },
              'href': 'https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI',
              'id': '12Chz98pHFMPJEknJQMWvI',
              'name': 'Muse',
              'type': 'artist',
              'uri': 'spotify:artist:12Chz98pHFMPJEknJQMWvI'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/5eJTvSeghTKoqN3Ly4TqEf'
          },
          'href': 'https://api.spotify.com/v1/albums/5eJTvSeghTKoqN3Ly4TqEf',
          'id': '5eJTvSeghTKoqN3Ly4TqEf',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/09f08a5296bed8f5658bdc8d7befc8d04294d41f',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/77fdcc5caeb6bd3cb4e84c7cb5ab0979934f48bf',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/d1e366b2a054053cf668fc33493ae2da440c92df',
              'width': 64
            }
          ],
          'name': 'Hullabaloo Soundtrack',
          'release_date': '2002',
          'release_date_precision': 'year',
          'total_tracks': 21,
          'type': 'album',
          'uri': 'spotify:album:5eJTvSeghTKoqN3Ly4TqEf'
        },
        {
          'album_type': 'album',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI'
              },
              'href': 'https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI',
              'id': '12Chz98pHFMPJEknJQMWvI',
              'name': 'Muse',
              'type': 'artist',
              'uri': 'spotify:artist:12Chz98pHFMPJEknJQMWvI'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/2EcBoQ1Hb39hgSUEgrtR3j'
          },
          'href': 'https://api.spotify.com/v1/albums/2EcBoQ1Hb39hgSUEgrtR3j',
          'id': '2EcBoQ1Hb39hgSUEgrtR3j',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/3da2ab75e1ca3f12eb48caeb2438aeae201acce7',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/b7c44d39e7385e1bdb41ffc70e2591317e4a2f7d',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/eaa91343326be9bfd483a865588133a00f5d9a4d',
              'width': 64
            }
          ],
          'name': 'HAARP (Live From Wembley Stadium)',
          'release_date': '2007-12-03',
          'release_date_precision': 'day',
          'total_tracks': 15,
          'type': 'album',
          'uri': 'spotify:album:2EcBoQ1Hb39hgSUEgrtR3j'
        },
        {
          'album_type': 'single',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI'
              },
              'href': 'https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI',
              'id': '12Chz98pHFMPJEknJQMWvI',
              'name': 'Muse',
              'type': 'artist',
              'uri': 'spotify:artist:12Chz98pHFMPJEknJQMWvI'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/3kVGhOkgwIS2S0Gf1El92G'
          },
          'href': 'https://api.spotify.com/v1/albums/3kVGhOkgwIS2S0Gf1El92G',
          'id': '3kVGhOkgwIS2S0Gf1El92G',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/50106757770524556953d3dc0108f0dbc911faea',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/785c999a6808824142f59673a708776c974bcd74',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/e6c894ca21ad7fa826f60a6f684eabe201a6a87e',
              'width': 64
            }
          ],
          'name': 'Dead Star / In Your World (Updated 2009)',
          'release_date': '2002',
          'release_date_precision': 'year',
          'total_tracks': 4,
          'type': 'album',
          'uri': 'spotify:album:3kVGhOkgwIS2S0Gf1El92G'
        },
        {
          'album_type': 'single',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/758yIKdhJhWL6oTuTSFVV6'
              },
              'href': 'https://api.spotify.com/v1/artists/758yIKdhJhWL6oTuTSFVV6',
              'id': '758yIKdhJhWL6oTuTSFVV6',
              'name': 'Dirk Maassen',
              'type': 'artist',
              'uri': 'spotify:artist:758yIKdhJhWL6oTuTSFVV6'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/5MooFJKqtOdgaXIBmLOzXQ'
          },
          'href': 'https://api.spotify.com/v1/albums/5MooFJKqtOdgaXIBmLOzXQ',
          'id': '5MooFJKqtOdgaXIBmLOzXQ',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/ed9b5e6f62785ffb0eee28f32bda3c4ccc805109',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/641a32ea7522d77774bf3ceecd0210139ecb5e31',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/573ca34ea5620404160b7915670235f184083650',
              'width': 64
            }
          ],
          'name': 'Muse',
          'release_date': '2018-05-11',
          'release_date_precision': 'day',
          'total_tracks': 1,
          'type': 'album',
          'uri': 'spotify:album:5MooFJKqtOdgaXIBmLOzXQ'
        },
        {
          'album_type': 'album',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/4vGrte8FDu062Ntj0RsPiZ'
              },
              'href': 'https://api.spotify.com/v1/artists/4vGrte8FDu062Ntj0RsPiZ',
              'id': '4vGrte8FDu062Ntj0RsPiZ',
              'name': 'Polyphia',
              'type': 'artist',
              'uri': 'spotify:artist:4vGrte8FDu062Ntj0RsPiZ'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/7EyDVKiEcQw9tE44UpcLWJ'
          },
          'href': 'https://api.spotify.com/v1/albums/7EyDVKiEcQw9tE44UpcLWJ',
          'id': '7EyDVKiEcQw9tE44UpcLWJ',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/64859fa60c44086c6161488236a0d6c3b22adee2',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/003033e7e76f2244e0e78f7cff7c6f546019c202',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/7352e2fde5ca0da88436ec73d06b0650f4af8e21',
              'width': 64
            }
          ],
          'name': 'Muse',
          'release_date': '2015-04-21',
          'release_date_precision': 'day',
          'total_tracks': 11,
          'type': 'album',
          'uri': 'spotify:album:7EyDVKiEcQw9tE44UpcLWJ'
        },
        {
          'album_type': 'single',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI'
              },
              'href': 'https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI',
              'id': '12Chz98pHFMPJEknJQMWvI',
              'name': 'Muse',
              'type': 'artist',
              'uri': 'spotify:artist:12Chz98pHFMPJEknJQMWvI'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/16rRWuAQcgHUNYs7u0hLTr'
          },
          'href': 'https://api.spotify.com/v1/albums/16rRWuAQcgHUNYs7u0hLTr',
          'id': '16rRWuAQcgHUNYs7u0hLTr',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/e757c4ddc322b554fc98ab6c4172fc1a74b6ef62',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/7a4b10da62095d2ed26e37a296b95f7c577a4718',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/65584d1c25e8fc21abc788124adef15251f795b4',
              'width': 64
            }
          ],
          'name': 'Hysteria (Updated 2009)',
          'release_date': '2003',
          'release_date_precision': 'year',
          'total_tracks': 2,
          'type': 'album',
          'uri': 'spotify:album:16rRWuAQcgHUNYs7u0hLTr'
        },
        {
          'album_type': 'single',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI'
              },
              'href': 'https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI',
              'id': '12Chz98pHFMPJEknJQMWvI',
              'name': 'Muse',
              'type': 'artist',
              'uri': 'spotify:artist:12Chz98pHFMPJEknJQMWvI'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/2UKLuY065mJeNfEgi4wiJ2'
          },
          'href': 'https://api.spotify.com/v1/albums/2UKLuY065mJeNfEgi4wiJ2',
          'id': '2UKLuY065mJeNfEgi4wiJ2',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/5de7a0b1db8ae5c47d118ceb47e18bb60046ae51',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/f817192f714b394d1c95fbee4afccef93d8d9091',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/0d2c67d19c2b91a3ccd6d225bfda2950ca4685e9',
              'width': 64
            }
          ],
          'name': 'Invincible (updated 09)',
          'release_date': '2007-04-09',
          'release_date_precision': 'day',
          'total_tracks': 4,
          'type': 'album',
          'uri': 'spotify:album:2UKLuY065mJeNfEgi4wiJ2'
        },
        {
          'album_type': 'album',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/1JdeDdujDbS6ZeSlkXqx3a'
              },
              'href': 'https://api.spotify.com/v1/artists/1JdeDdujDbS6ZeSlkXqx3a',
              'id': '1JdeDdujDbS6ZeSlkXqx3a',
              'name': 'Loreena McKennitt',
              'type': 'artist',
              'uri': 'spotify:artist:1JdeDdujDbS6ZeSlkXqx3a'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/2QA8wSVwRjy0kYMHhgo0Qp'
          },
          'href': 'https://api.spotify.com/v1/albums/2QA8wSVwRjy0kYMHhgo0Qp',
          'id': '2QA8wSVwRjy0kYMHhgo0Qp',
          'images': [
            {
              'height': 600,
              'url': 'https://i.scdn.co/image/27b9ece34e6c5b00fb4065d75c354a5228dcc4c0',
              'width': 600
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/1c068265e1d4cec6c14e2e51b3c651bd4fbae2c6',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/bac8775793c3b0f5de25489eb35c3ae400fd556a',
              'width': 64
            }
          ],
          'name': 'An Ancient Muse',
          'release_date': '2006',
          'release_date_precision': 'year',
          'total_tracks': 9,
          'type': 'album',
          'uri': 'spotify:album:2QA8wSVwRjy0kYMHhgo0Qp'
        },
        {
          'album_type': 'single',
          'artists': [
            {
              'external_urls': {
                'spotify': 'https://open.spotify.com/artist/12Chz98pHFMPJEknJQMWvI'
              },
              'href': 'https://api.spotify.com/v1/artists/12Chz98pHFMPJEknJQMWvI',
              'id': '12Chz98pHFMPJEknJQMWvI',
              'name': 'Muse',
              'type': 'artist',
              'uri': 'spotify:artist:12Chz98pHFMPJEknJQMWvI'
            }
          ],
          'available_markets': [
            'AD',
            'AE',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BH',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IS',
            'IT',
            'JO',
            'JP',
            'KW',
            'LB',
            'LI',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PH',
            'PL',
            'PS',
            'PT',
            'PY',
            'QA',
            'RO',
            'SA',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TN',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'
          ],
          'external_urls': {
            'spotify': 'https://open.spotify.com/album/445uybhAr9ey555kQ6gahx'
          },
          'href': 'https://api.spotify.com/v1/albums/445uybhAr9ey555kQ6gahx',
          'id': '445uybhAr9ey555kQ6gahx',
          'images': [
            {
              'height': 640,
              'url': 'https://i.scdn.co/image/5cd27fff78dba4949a9b99a9391a8962d9c160cd',
              'width': 640
            },
            {
              'height': 300,
              'url': 'https://i.scdn.co/image/e6596d8b33ea61dab2d89e4f56d2168b0d0c048d',
              'width': 300
            },
            {
              'height': 64,
              'url': 'https://i.scdn.co/image/607013502778aba4b941c6ea9e4e3416f4b396cf',
              'width': 64
            }
          ],
          'name': 'Supermassive Black Hole (Updated 2009)',
          'release_date': '2006-06-17',
          'release_date_precision': 'day',
          'total_tracks': 2,
          'type': 'album',
          'uri': 'spotify:album:445uybhAr9ey555kQ6gahx'
        }
      ],
      'limit': 20,
      'next': 'https://api.spotify.com/v1/search?query=muse&type=album&market=IT&offset=20&limit=20',
      'offset': 0,
      'previous': null,
      'total': 1346
    }
  };
}
